### ISSUE TITLE
Dataset Release

### ISSUE THREAD

**Issue by aartykov** [ChaoyueSong/REACTO#2]
Hello!

Thanks for the great work. Where can I get the real-world video dataset that you used to evaluate your method?

Thanks!

**Comment by ChaoyueSong** [comment]
Hi @aartykov, sorry for the late reply. Please check https://huggingface.co/datasets/chaoyue7/reacto_data for the preprocessed data.

**Comment by aartykov** [comment]
Hello! Thanks for the dataset. Which of the camera pose files do you use as world2cam poses?

**Comment by ChaoyueSong** [comment]
Hello, we use `bg.npy` for the world-to-camera transformation and `00.npy` for the object-to-camera transformation of the first object. If there are additional objects, you might also see files like `01.npz`, `02.npz`, etc.

**Comment by aartykov** [comment]
Hello again. When I visualize sequential point cloud(for example for synthetic stapler data) by using bg.npy as camera poses, the whole point cloud does wierd motion. Should not the static part of the stapler be static throughout the video?

**Comment by ChaoyueSong** [comment]
For synthetic data, they are indeed static with respect to bg. You can check the original video from JPEGImagesRaw using ffmpeg.

**Comment by aartykov** [comment]
Thanks for quick answer! Since the depth maps has smaller size, do you suggest to use rgb and masks resized to the size of depth maps?

**Comment by aartykov** [comment]
Finally, why dont you use true GT data for the synthetic scenes, but rather estimate them with Lab4D framework?

**Comment by aartykov** [comment]
Hello. We have tried to reproduce your experiments. There is something we don't understand concerning your file format. According to you, bg.npy gives us world-to-camera poses. However, when trying to display the dataset using these poses we encounter some issues. Yet, when displaying the data using your depth map, but with COLMAP poses and intrinsics, we have consistent results. Are you sure that camera poses in bg.npy are simply absolute world-to-camera poses, and not relative poses?
